### ISSUE TITLE
Installation instructions lacking

### ISSUE THREAD

**Issue by JRMeyer** [apertium/apertium-kir#1]
Hey JNW, Fran, et al.

The listed dependencies:

* lttoolbox
* Apertium
* HFST
* VISLCG3 

don't have any links or instructions for installation, which would be helpful.

-josh

**Comment by TinoDidriksen** [comment]
Correct. Forwarded to https://github.com/apertium/organisation/issues/1 - for now, see http://wiki.apertium.org/wiki/Installation

**Comment by JRMeyer** [comment]
thanks, Tino!

**Comment by JRMeyer** [comment]
Hi All, 

I closed this too early, it seems.

I followed the installation instructions that Tino pointed too, but there's no documentation *anywhere* on the wiki or github about using the Kyrgyz transducer.

I would love to be wrong here!

-josh

**Comment by TinoDidriksen** [comment]
A quick search says you're right. If one knows where to look, it can be found under http://wiki.apertium.org/wiki/Documentation -> http://xixona.dlsi.ua.es/~fran/apertium2-documentation.pdf page 123 at least.

The available modes are listed in https://github.com/apertium/apertium-kir/blob/master/modes.xml

If you installed globally, then it's something like `echo "Kyrgyz text goes here" | apertium kir-disam`, and if you only built it then from the apertium-kir folder you can do `echo "Kyrgyz text goes here" | apertium -d . kir-disam`

For development, you should keep it in the folder and not run `make install`. If you want a global install, use the prebuilt packages.

**Comment by JRMeyer** [comment]
That documentation is great!
I also found that "tagger" may have been a better search term vs. "transducer".

I found somewhere a reference to `xxx-tagger`, and tried out `kir-tagger`, and got something I want:

```
$ echo "Ахмет мектепке кетти." | apertium -d . kir-tagger
^Ахмет/Ахмет<np><ant><m><nom>$ ^мектепке/мектеп<n><dat>$ ^кетти/кет<v><iv><ifi><p3><sg>$^../..<sent>$
```

I'll take some time to study that documentation.

In the meantime, could you comment on using `kir-disam` vs `kir-tagger`?

Thanks for the super-quick reply!

**Comment by TinoDidriksen** [comment]
As I don't work with the language, not really. You can inspect https://github.com/apertium/apertium-kir/blob/master/modes.xml and see exactly what command chain is behind the aliases, then compare what outputs they give.

**Comment by JRMeyer** [comment]
I see, I should study the docs / modes then.

Thanks!

**Comment by jonorthwash** [comment]
Sorry @JRMeyer, just saw this.  Yes, we should really document things better...  Let's talk on IRC or Hangouts or something about any remaining questions you might have, and I can try to figure out from there how to document stuff.
